title: Hades' Star Community Data
description: A detailed scoreboard of top corporations based on Elo ratings and historic whitestar results in several formats (csv, json, xlsx)
theme: minima
markdown: kramdown
permalink: pretty

# Minima theme settings
minima:
  skin: dark

# Navigation
header_pages:
  - index.md
  - top100.md
  - comp100.md

# Site properties
language: english
