title: Hades' Star Community Data
description: A detailed scoreboard of top corporations based on Elo ratings and historic whitestar results in several formats (csv, json, xlsx)
remote_theme: minima
markdown: kramdown
permalink: pretty

# Minima theme settings
minima:
  skin: dark

# Navigation
header_pages:
  - index.md
  - top100.md
  - comp100.md

# Custom navigation bar
nav:
  - name: Home
    link: /
  - name: Top 100 Elo Ratings
    link: /top100.md
  - name: Top 100 Competitive Elo Ratings
    link: /comp100.md

# Site properties
language: english
